=== kofalt/core/swagger/schemas/mongo/subject.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id":              {},
    "firstname":        { "type": "string" },
    "lastname":         { "type": "string" },

    "project":          {},
    "created":          {},
    "modified":         {},
    "revision":         {},
    "permissions":      {},
    "public":           {},

    "sex":              { "$ref": "../definitions/subject.json#/definitions/sex" },
    "cohort":           { "$ref": "../definitions/subject.json#/definitions/cohort" },
    "type":             { "$ref": "../definitions/subject.json#/definitions/type" },
    "race":             { "$ref": "../definitions/subject.json#/definitions/race" },
    "ethnicity":        { "$ref": "../definitions/subject.json#/definitions/ethnicity" },
    "species":          { "type": "string" },
    "strain":           { "type": "string" },

    "code":             { "type": "string" },
    "master_code":      { "type": "string" },
    "label":            { "type": "string" },
    "tags":             { "type": "array", "items": {"type": "string"} },
    "files":            {
                          "type": ["array", "null"],
                          "items": {"$ref": "file.json"}
                        },
    "info":             { "type": "object" }
  },
  "additionalProperties": false
}

=== kofalt/core/swagger/examples/output/subject.json
{
    "_id": "57e01cccb1dc04000fb83f02",
    "project": "57e01cccf6b5d5edbcb4e1cf",
    "code": "ex4784",

    "firstname": "Johnny",
    "lastname": "Appleseed",
    "sex": "male",
    "type": "human",
    "race": "More Than One Race",
    "ethnicity": "Not Hispanic or Latino",
    "cohort": "Validation",

    "created": "2016-09-19T17:13:48.164000+00:00",
    "modified": "2016-09-19T17:13:48.164000+00:00",
    "public": false,
    "permissions": [{
        "access": "admin",
        "_id": "57e01cccf6b5d5ed2cb4e182"
    }]
}

=== kofalt/core/swagger/examples/output/subject-list.json
[{
    "_id": "57e01cccb1dc04000fb83f02",
    "project": "57e01cccf6b5d5edbcb4e1cf",
    "code": "ex4784",
    "type": "human",
    "race": "More Than One Race",
    "cohort": "Control",
    "created": "2016-09-19T17:13:48.164000+00:00",
    "modified": "2016-09-19T17:13:48.164000+00:00",
    "public": false,
    "permissions": [{
        "access": "admin",
        "_id": "57e01cccf6b5d5ed2cb4e182"
    }]
}, {
    "_id": "57e01cccb1dc04000fb83f56",
    "project": "57e01cccf6b5d5edbcb4e182",
    "code": "ex1366",
    "type": "animal",
    "species": "rat",
    "cohort": "Training",
    "created": "2016-09-20T17:13:48.164000+00:00",
    "modified": "2016-09-20T17:13:48.164000+00:00",
    "public": true,
    "permissions": [{
        "access": "admin",
        "_id": "57e01cccf6b5d5ed2cb4e182"
    }]
}]
